### PR TITLE
DM-9756: Add cmake version and reference platform

### PR DESCRIPTION
**Pull request by timj**

### CODE REVIEW

**Comment by timj** [comment]
I've added the reference platform note here even though it's technically part of another ticket.

**Comment by jonathansick** [comment]
I think we need to put this PR on hold until after 14.0 is merged because of significant changes/refactoring. All of the cmake changes can wait until after the 14.0 release, correct?

**Comment by timj** [comment]
@jonathansick in this PR we say:
> Our reference platform is CentOS 7, and we require a minimum version of 7-1611.

but for the 14.0 release I think we do need to say something like:

> Our reference platform is CentOS 7-1611.

because that is true. That's what we are running at NCSA.

**Comment by timj** [comment]
@jonathansick @ktlim I've cleaned up this PR following the merge of 14.0. Can you please take another look?

**Comment by jonathansick** [comment]
Could you move this statement to the `prereqs/*` pages? That's where we're centralizing prerequisite info (`lsstsw` also points to the prereqs pages).

**Comment by timj** [comment]
Are we really saying that every prereq page has to individual list all prereq version numbers? Seems like work. I understand that the gcc one is not relevant to macOS but cmake is. I won't be able to make this change this week.

**Comment by jonathansick** [comment]
> Are we really saying that every prereq page has to individual list all prereq version numbers?

It'd be great to have a table of prereqs and the min/max version ranges. *However,* I'm not suggesting we do that in this PR.

I'm suggesting that your paragraph currently in `install/newinstall.rst` should be moved to `prereqs/index.rst`. Since the macOS prereq page talks about cmake in some detail you _could_ also put the version there, but not required (I know we'd want to single-source this better).

All I was getting at is that we have two ways of building by source (lsstsw and newinstall) and to make those docs work, we're collecting all prereq notices in a centralized prereqs page.

**Comment by timj** [comment]
@jonathansick I've updated to do what you wanted. Does that look okay now?

**Pull request merged**
