### PR TITLE
Demo Instructions Update

### PR DESCRIPTION
**Pull request by wtgee**
Add a note about which version of the demo data to use.

### CODE REVIEW

**Comment by timj** [comment]
I think this pull request has brought in too many commits. It would be clearer if we knew we were only merging the single commit into the release branch. @jonathansick we probably need the commit on master as well.

**Comment by wtgee** [comment]
@timj Yeah, sorry, I was trying to patch off of github direct and it forked from master. I can close this and branch from `13.0` direct. (I just tried a rebase from `13.0` but didn't seem to do the trick)

**Comment by timj** [comment]
@jonathansick may prefer it as a patch to master and a cherry-pick to the release branch (ie you might be able to get away with changing the target branch of the PR)

**Comment by jonathansick** [comment]
Thanks @wtgee, this is a good idea. Tim's right, we just need a PR off `master`; I'm not sure if the extra merge commit at the end will mess things up.

If you get a chance, could you put the clone instructions into the note? Something like:

```rst
.. note::

   The demo's version should match your installed software.
   If you are building from source (with :doc:`lsstsw <lsstsw>`), clone the demo repository instead of downloading a release:

   .. code-block:: bash

      git clone https://github.com/lsst/lsst_dm_stack_demo.git
```

**Comment by wtgee** [comment]
Moved to https://github.com/lsst/pipelines_lsst_io/pull/44

**Pull request closed without merging**
